name: ignitr_template
description: A flutter's mini framework to kickstart flutter projects with ease.

publish_to: "none"

version: 0.1.1+1

environment:
  sdk: ^3.6.0

dependencies:
  core:
    path: core
  flutter:
    sdk: flutter

  get: ^4.6.6
  feather_icons: ^1.2.0
  flutter_svg: ^2.0.17
  google_fonts: ^8.0.2
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^6.0.0
  faker: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

# Launcher Icon Configs
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
